import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      paddingHorizontal: Spacing.xl,
      paddingTop: Spacing.xl,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: Spacing.xl,
    },
    title: {
      fontSize: 24,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    adminInfo: {
      alignItems: 'center',
      paddingVertical: Spacing.xl,
      backgroundColor: theme.primary + '15',
      borderRadius: BorderRadius.lg,
      marginBottom: Spacing.xl,
    },
    adminTitle: {
      fontSize: 16,
      color: theme.primary,
      marginTop: Spacing.sm,
      fontWeight: '600',
    },
    adminName: {
      fontSize: 20,
      fontWeight: '700',
      color: theme.textPrimary,
      marginTop: Spacing.xs,
    },
    listHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.md,
    },
    listTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    listCount: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    userList: {
      flex: 1,
    },
    userItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.md,
      marginBottom: Spacing.xs,
      borderRadius: BorderRadius.md,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: theme.border,
    },
    userAvatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.primary + '15',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: Spacing.sm,
    },
    userInfo: {
      flex: 1,
    },
    userName: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textPrimary,
      lineHeight: 18,
    },
    userMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      marginTop: 1,
      gap: Spacing.sm,
    },
    userNickname: {
      fontSize: 11,
      color: theme.textSecondary,
      lineHeight: 14,
    },
    userDetail: {
      fontSize: 11,
      color: theme.textMuted,
      lineHeight: 14,
    },
    userActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    actionButton: {
      width: 32,
      height: 32,
      borderRadius: BorderRadius.sm,
      justifyContent: 'center',
      alignItems: 'center',
    },
    adminBadge: {
      backgroundColor: theme.primary,
      paddingHorizontal: Spacing.xs,
      paddingVertical: 2,
      borderRadius: BorderRadius.xs,
    },
    adminBadgeText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: '600',
    },
    logoutButton: {
      width: '100%',
      backgroundColor: theme.error || '#FF4444',
      paddingVertical: Spacing.lg,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      marginTop: Spacing.md,
      marginBottom: Spacing.xl,
    },
    logoutButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '600',
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingBottom: Spacing['5xl'],
    },
    emptyText: {
      fontSize: 20,
      fontWeight: '600',
      color: theme.textMuted,
      marginTop: Spacing.lg,
    },
    emptySubText: {
      fontSize: 14,
      color: theme.textSecondary,
      marginTop: Spacing.sm,
    },
    deleteButton: {
      justifyContent: 'center',
      alignItems: 'center',
      width: 80,
      marginBottom: Spacing.md,
      borderRadius: BorderRadius.lg,
      marginLeft: Spacing.sm,
    },
    deleteButtonText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: '600',
      marginTop: Spacing.xs,
    },
    // Modal样式
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: Spacing.xl,
    },
    modalContent: {
      width: '100%',
      maxWidth: 400,
      backgroundColor: '#FFFFFF',
      borderRadius: BorderRadius.xl,
      overflow: 'hidden',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: Spacing.lg,
      borderBottomWidth: 1,
      borderBottomColor: '#E5E7EB',
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: '#111827',
    },
    modalBody: {
      padding: Spacing.lg,
    },
    modalLabel: {
      fontSize: 14,
      fontWeight: '500',
      color: '#374151',
      marginBottom: Spacing.sm,
    },
    modalInput: {
      width: '100%',
      padding: Spacing.md,
      borderRadius: BorderRadius.md,
      borderWidth: 1,
      fontSize: 16,
    },
    modalFooter: {
      flexDirection: 'row',
      gap: Spacing.md,
      padding: Spacing.lg,
      borderTopWidth: 1,
      borderTopColor: '#E5E7EB',
    },
    modalButton: {
      flex: 1,
      paddingVertical: Spacing.md,
      borderRadius: BorderRadius.md,
      alignItems: 'center',
    },
    modalCancelButton: {
      backgroundColor: '#F3F4F6',
    },
    modalCancelButtonText: {
      color: '#374151',
      fontSize: 16,
      fontWeight: '600',
    },
    modalConfirmButton: {
      backgroundColor: '#4F46E5',
    },
    modalConfirmButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '600',
    },
    // 选项卡样式
    tabs: {
      flexDirection: 'row',
      backgroundColor: '#FFFFFF',
      borderRadius: BorderRadius.lg,
      marginBottom: Spacing.lg,
      borderWidth: 1,
      borderColor: theme.border,
      overflow: 'hidden',
    },
    tab: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: Spacing.md,
      gap: Spacing.sm,
      position: 'relative',
    },
    activeTab: {
      backgroundColor: theme.primary + '15',
    },
    tabText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    badge: {
      position: 'absolute',
      top: 6,
      right: 6,
      minWidth: 18,
      height: 18,
      backgroundColor: theme.error || '#FF4444',
      borderRadius: 9,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 4,
    },
    badgeText: {
      color: '#FFFFFF',
      fontSize: 10,
      fontWeight: '700',
    },
    // 反馈相关样式
    feedbackItem: {
      backgroundColor: '#FFFFFF',
      borderRadius: BorderRadius.md,
      padding: Spacing.md,
      marginBottom: Spacing.sm,
      borderWidth: 1,
      borderColor: theme.border,
    },
    feedbackHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: Spacing.sm,
    },
    feedbackUser: {
      flex: 1,
    },
    feedbackUserName: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textPrimary,
      marginBottom: 2,
    },
    feedbackContact: {
      fontSize: 12,
      color: theme.textSecondary,
    },
    feedbackStatus: {
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: BorderRadius.sm,
    },
    feedbackStatusText: {
      color: '#FFFFFF',
      fontSize: 11,
      fontWeight: '600',
    },
    feedbackContent: {
      fontSize: 14,
      color: theme.textPrimary,
      lineHeight: 20,
      marginBottom: Spacing.sm,
    },
    feedbackReply: {
      backgroundColor: theme.primary + '15',
      borderRadius: BorderRadius.sm,
      padding: Spacing.sm,
      marginBottom: Spacing.sm,
    },
    feedbackReplyLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.primary,
      marginBottom: 2,
    },
    feedbackReplyText: {
      fontSize: 13,
      color: theme.textPrimary,
      lineHeight: 18,
    },
    feedbackTime: {
      fontSize: 11,
      color: theme.textMuted,
      textAlign: 'right',
    },
    loadingContainer: {
      padding: Spacing.xl,
      alignItems: 'center',
    },
    loadingText: {
      color: theme.textMuted,
      fontSize: 14,
    },
    // 反馈详情
    feedbackDetail: {
      marginBottom: Spacing.lg,
    },
    feedbackDetailLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.textPrimary,
      marginBottom: Spacing.sm,
    },
    feedbackDetailText: {
      fontSize: 14,
      color: theme.textSecondary,
      lineHeight: 20,
    },
    statusOptions: {
      flexDirection: 'row',
      gap: Spacing.sm,
      flexWrap: 'wrap',
    },
    statusOption: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: BorderRadius.sm,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      backgroundColor: '#FFFFFF',
    },
    statusOptionText: {
      fontSize: 13,
      color: theme.textPrimary,
      fontWeight: '500',
    },
    textArea: {
      width: '100%',
      minHeight: 80,
      borderRadius: BorderRadius.md,
      padding: Spacing.md,
      borderWidth: 1,
      fontSize: 14,
      lineHeight: 20,
      textAlignVertical: 'top',
    },
  });
};
